WIDTH = 800
HEIGHT = 600

TEXTURE_IDLE = 0
TEXTURE_LEFT = 1
TEXTURE_RIGHT = 2

ZOMBIE_SPEED = 2.2
PLAYER_SPEED_POSITIVE = 2.8
PLAYER_SPEED_NEGATIVE = -2.8
COIN_COUNT = 100

SPRITE_SCALING_COIN = 0.2
SPRITE_SCALING_ZOMBIE = 1
SPRITE_SCALING_PLAYER = 1
