import random
WIDTH = 800
HEIGHT = 600

TEXTURE_IDLE = 0
TEXTURE_LEFT = 1
TEXTURE_RIGHT = 2

LEVEL1_ZOMBIE_SPEED = random.randrange(1, 3)
PLAYER_SPEED = 4
COIN_COUNT = 120

SPRITE_SCALING_COIN = 0.2
SPRITE_SCALING_ZOMBIE = 1
SPRITE_SCALING_PLAYER = 1
